### ISSUE TITLE
Authentication broken

### ISSUE THREAD

**Issue by Jesus-M** [badger707/esb-smart-meter-reading-automation#3]
Nice piece of work that I've been using for few months now.

The only login failures I found were when the actual ESBN website was failing.

Today anyway it stopped working while the ESBN website seems to be fine. I fear they changed something on their code and now the authentication is broken. After the line `print("[+] calling login page. ..")` the script breaks.

I tried to take a look but my knowledge is so limited I cannot find the problem.

Thanks for your work.

**Comment by badger707** [comment]
Yes, saw it, I have made the change, see it it works on your setup.
