### ISSUE TITLE
Pulling data

### ISSUE THREAD

**Issue by vitopiepoli** [badger707/esb-smart-meter-reading-automation#6]
The data is no more available using the code proposed.
At  line 65 it returns a HTML page, probably error page message.
How do we get the new query schema or parameters to be passed?

**Comment by vitopiepoli** [comment]
My understanding is that the code goes directly to the source of the data.
It would be great to know the new schema.

**Comment by Jesus-M** [comment]
Yes, but the source has changed now.

**Comment by vitopiepoli** [comment]
Agree, we need to know if that is even feasible now.

**Comment by badger707** [comment]
I'm looking at this.

**Comment by badger707** [comment]
I have it working now, need to tidy-up the code and will push the changes tomorrow.

**Comment by vitopiepoli** [comment]
That is great.
I had to write a bit with selenium to download the csv file and import in my analytics.
Would you mind to briefly explain what changed?

**Comment by badger707** [comment]
Yes, look at comment from @Jesus-M

**Comment by vitopiepoli** [comment]
Sorry, I did not explain myself well.

I have seen that they changed the source but I was wondering what did you change in your code to get the data for the ESB database.
Would you also be interested getting the piece of code I wrote to download the 30 minutes csv file?

**Comment by badger707** [comment]
Closing, code updated to reflect new changes.

**Comment by Jesus-M** [comment]
The changes work fine, thanks for that, but maybe there is a 'print' missing at the end?

**Comment by badger707** [comment]
@Jesus-M jus add print on json_out.

**Comment by Jesus-M** [comment]
Yes, that's what I did to test the changes, although in my final use of it, I will go with CSV.

Thanks once again for the work!!
